server:
  port: 9024
  # graceful shutdown makes sure we have time to finnish any ongoing rest requests before terminating
  # default value will be 30s before terminating
  shutdown: graceful

spring:
  application:
    name: va-corporate-srv
  servlet:
    multipart:
      enabled: true
      maxFileSize: 300000
      maxRequestSize: 300000
      location: ${java.io.tmpdir}
  datasource:
#    url: jdbc:postgresql://91.108.104.69:5433/va_cms?prepareThreshold=0
#    driver-class-name: org.postgresql.Driver
#    username: postgres
#    password: ak4r01092023#@
#    hikari.connectionTimeout: 100000
#    hikari.idleTimeout: 600000
#    hikari.maxLifetime: 1800000
    va-cms:
      url: jdbc:postgresql://${DB1_HOST:91.108.104.69}:${DB1_PORT:5433}/${DB1_DBNAME:va_cms}?prepareThreshold=0
      driver-class-name: org.postgresql.Driver
      username: ${DB1_USERNAME:postgres}
      password: ${DB1_PASSWORD:ak4r01092023#@}
      hikari.connectionTimeout: 100000
      hikari.idleTimeout: 600000
      hikari.maxLifetime: 1800000
    va-v2:
      url: jdbc:postgresql://${DB2_HOST:91.108.104.69}:${DB2_PORT:5433}/${DB2_DBNAME:va_v2}?prepareThreshold=0
      driver-class-name: org.postgresql.Driver
      username: ${DB2_USERNAME:postgres}
      password: ${DB2_PASSWORD:ak4r01092023#@}
      hikari.connectionTimeout: 100000
      hikari.idleTimeout: 600000
      hikari.maxLifetime: 1800000

  liquibase:
    enabled: false
    change-log: classpath:db/changelog-master.xml

#springdoc:
#  api-docs:
#    path: /authentication-docs
#  swagger-ui:
#    path: /authentication-docs/swagger-ui-custom.html

logging.level:
  root: INFO
  liquibase: INFO