server:
  port: 9018
  # graceful shutdown makes sure we have time to finnish any ongoing rest requests before terminating
  # default value will be 30s before terminating
  shutdown: graceful

spring:
  application:
    name: server-auth
  datasource:
    url: jdbc:postgresql://91.108.104.69:5433/nwn_auth?prepareThreshold=0
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: ak4r01092023#@
    hikari.connectionTimeout: 100000
    hikari.idleTimeout: 600000
    hikari.maxLifetime: 1800000

  liquibase:
    enabled: true
    change-log: classpath:db/changelog-master.xml

#springdoc:
#  api-docs:
#    path: /authentication-docs
#  swagger-ui:
#    path: /authentication-docs/swagger-ui-custom.html

logging.level:
  root: INFO
  liquibase: INFO