package com.bjbs.auth.models;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Branch generated by hbm2java
 */

@Entity
@Table(name = "branch", schema = "public")
public class Branch implements java.io.Serializable {

	private static final long serialVersionUID = 5022012690664998519L;

	private long branchId;
	private String branchCode;
	private String branchName;
	private String branchAddress;
	private Date createdDate;
	private String createdBy;
	private Date updatedDate;
	private String updatedBy;

	public Branch() {
	}

	public Branch(long branchId) {
		this.branchId = branchId;
	}

	public Branch(long branchId, String branchCode, String branchName, String branchAddress, Date createdDate,
			String createdBy, Date updatedDate, String updatedBy) {
		this.branchId = branchId;
		this.branchCode = branchCode;
		this.branchName = branchName;
		this.branchAddress = branchAddress;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.updatedDate = updatedDate;
		this.updatedBy = updatedBy;
	}
	
	@Id
	@Column( name = "branch_id", nullable = false, unique = true)
	public long getBranchId() {
		return this.branchId;
	}

	public void setBranchId(long branchId) {
		this.branchId = branchId;
	}
	
	@Column( name = "branch_code")
	public String getBranchCode() {
		return this.branchCode;
	}

	public void setBranchCode(String branchCode) {
		this.branchCode = branchCode;
	}
	
	@Column( name = "branch_name")
	public String getBranchName() {
		return this.branchName;
	}

	public void setBranchName(String branchName) {
		this.branchName = branchName;
	}
	
	@Column( name = "branch_address")
	public String getBranchAddress() {
		return this.branchAddress;
	}
	
	public void setBranchAddress(String branchAddress) {
		this.branchAddress = branchAddress;
	}
	
	@Column( name = "created_date", columnDefinition = "DATE")
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}
	
	@Column( name = "created_by")
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}
	
	@Column( name = "updated_date", columnDefinition = "DATE")
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}
	
	@Column( name = "updated_by")
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

}
