package com.bjbs.auth.models;
// Generated Sep 9, 2019 4:24:42 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Menu generated by hbm2java
 */
@Entity
@Table(name = "menu", schema = "public")
public class Menu implements java.io.Serializable {

	private long menuId;
	private String menuName;
	private String menuDescription;
	private String menuCategory;
	private String menuPath;
	private Set<RoleMenu> roleMenus = new HashSet<RoleMenu>(0);

	public Menu() {
	}

	public Menu(long menuId) {
		this.menuId = menuId;
	}

	public Menu(long menuId, String menuName, String menuDescription, String menuCategory, String menuPath,
			Set<RoleMenu> roleMenus) {
		super();
		this.menuId = menuId;
		this.menuName = menuName;
		this.menuDescription = menuDescription;
		this.menuCategory = menuCategory;
		this.menuPath = menuPath;
		this.roleMenus = roleMenus;
	}

	@Id
	@Column(name = "menu_id", unique = true, nullable = false)
	public long getMenuId() {
		return this.menuId;
	}

	public void setMenuId(long menuId) {
		this.menuId = menuId;
	}

	@Column(name = "menu_name", length = 50)
	public String getMenuName() {
		return this.menuName;
	}

	public void setMenuName(String menuName) {
		this.menuName = menuName;
	}

	@Column(name = "menu_description")
	public String getMenuDescription() {
		return this.menuDescription;
	}

	public void setMenuDescription(String menuDescription) {
		this.menuDescription = menuDescription;
	}

	@Column(name = "menu_category", length = 50)
	public String getMenuCategory() {
		return this.menuCategory;
	}

	public void setMenuCategory(String menuCategory) {
		this.menuCategory = menuCategory;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "menu")
	public Set<RoleMenu> getRoleMenus() {
		return this.roleMenus;
	}

	public void setRoleMenus(Set<RoleMenu> roleMenus) {
		this.roleMenus = roleMenus;
	}
	
	@Column(name = "menu_path")
	public String getMenuPath() {
		return menuPath;
	}

	public void setMenuPath(String menuPath) {
		this.menuPath = menuPath;
	}

}
