package com.bjbs.auth.models;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * UserBranch generated by hbm2java
 */

@Entity
@Table(name = "user_branch", schema = "public")
public class UserBranch implements java.io.Serializable {

	private static final long serialVersionUID = 8927863450075880846L;

	private long userBranchId;
	private Branch branch;
	private Users user;
	private Date createdDate;
	private String createdBy;
	private Date updatedDate;
	private String updatedBy;

	public UserBranch() {
	}

	public UserBranch(long userBranchId, Branch branch) {
		this.userBranchId = userBranchId;
		this.branch = branch;
	}

	public UserBranch(long userBranchId, Branch branch, Users user, Date createdDate, String createdBy,
			Date updatedDate, String updatedBy) {
		this.userBranchId = userBranchId;
		this.branch = branch;
		this.user = user;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.updatedDate = updatedDate;
		this.updatedBy = updatedBy;
	}
	
	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator_user_branch_user_branch_seq")
	@SequenceGenerator(name="generator_user_branch_user_branch_seq", sequenceName="user_branch_user_branch_seq", schema = "public", allocationSize = 1)
	@Column( name = "user_branch_id", nullable = false, unique = true)
	public long getUserBranchId() {
		return this.userBranchId;
	}

	public void setUserBranchId(long userBranchId) {
		this.userBranchId = userBranchId;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn( name = "branch_id")
	public Branch getBranch() {
		return this.branch;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn( name = "user_id")
	public Users getUser() {
		return user;
	}

	public void setUser(Users user) {
		this.user = user;
	}

	public void setBranch(Branch branch) {
		this.branch = branch;
	}
	
	@Column( name = "created_date", columnDefinition = "DATE")
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}
	
	@Column( name = "created_by")
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}
	
	@Column( name = "updated_date", columnDefinition = "DATE")
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}
	
	@Column( name = "updated_by")
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

}
