package com.bjbs.auth.models;
// Generated Sep 9, 2019 4:24:42 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserRole generated by hbm2java
 */
@Entity
@Table(name = "user_role", schema = "public")
public class UserRole implements java.io.Serializable {

	private long userRoleId;
	private Role role;
	private Users users;
	private Date availableDate;

	public UserRole() {
	}

	public UserRole(long userRoleId) {
		this.userRoleId = userRoleId;
	}

	public UserRole(long userRoleId, Role role, Users users, Date availableDate) {
		this.userRoleId = userRoleId;
		this.role = role;
		this.users = users;
		this.availableDate = availableDate;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator_user_role_user_role_id_seq")
	@SequenceGenerator(name="generator_user_role_user_role_id_seq", sequenceName="user_role_user_role_id_seq", schema = "public", allocationSize = 1)
	@Column(name = "user_role_id", unique = true, nullable = false)
	public long getUserRoleId() {
		return this.userRoleId;
	}

	public void setUserRoleId(long userRoleId) {
		this.userRoleId = userRoleId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "role_id")
	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id")
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "available_date", length = 13)
	public Date getAvailableDate() {
		return this.availableDate;
	}

	public void setAvailableDate(Date availableDate) {
		this.availableDate = availableDate;
	}

}
