package com.bjbs.auth.models;
// Generated Sep 9, 2019 4:24:42 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "users", schema = "public")
public class Users implements java.io.Serializable {

	private Long userId;
	private String userName;
	private String userEmail;
	private String userPhoneNumber;
	private String userMotto;
	private String userLinkedInUrl;
	private Date userBirthdate;
	private String userBirthplace;
	private String password;
	private Short userGender;
	private String userAddress;
	private String userPostalCode;
	private String userFeedbackMethod;
	private String userLifestyleAspiration;
	private String userRedflags;
	private String userPredictableTimeOff;
	private String userImageProfile;
	private Short userMaritalStatus;
	private Short isActive;
	private Short isFreshUser;
	private String userRealName;
	private Date createdDate;
	private String createdBy;
	private Date updatedDate;
	private String updatedBy;
	private Set<UserRole> userRoles = new HashSet<UserRole>(0);

	public Users() {
	}

	public Users(Long userId, String userPhoneNumber, String userMotto) {
		this.userId = userId;
		this.userPhoneNumber = userPhoneNumber;
		this.userMotto = userMotto;
	}

	public Users(Long userId, String userName, String userEmail, String userPhoneNumber, String userMotto,
			String userLinkedInUrl, Date userBirthdate, String userBirthplace, Short userGender, String userAddress,
			String userPostalCode, String userFeedbackMethod, String userLifestyleAspiration, String userRedflags,
			String userPredictableTimeOff, String userImageProfile, Short userMaritalStatus, Short isActive,
			Short isFreshUser, String userRealName, Set<UserRole> userRoles) {
		this.userId = userId;
		this.userName = userName;
		this.userEmail = userEmail;
		this.userPhoneNumber = userPhoneNumber;
		this.userMotto = userMotto;
		this.userLinkedInUrl = userLinkedInUrl;
		this.userBirthdate = userBirthdate;
		this.userBirthplace = userBirthplace;
		this.userGender = userGender;
		this.userAddress = userAddress;
		this.userPostalCode = userPostalCode;
		this.userFeedbackMethod = userFeedbackMethod;
		this.userLifestyleAspiration = userLifestyleAspiration;
		this.userRedflags = userRedflags;
		this.userPredictableTimeOff = userPredictableTimeOff;
		this.userImageProfile = userImageProfile;
		this.userMaritalStatus = userMaritalStatus;
		this.isActive = isActive;
		this.isFreshUser = isFreshUser;
		this.userRealName = userRealName;
		this.userRoles = userRoles;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "user_id", unique = true, nullable = false)
	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	@Column(name = "user_name", length = 50)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "user_email", length = 50)
	public String getUserEmail() {
		return this.userEmail;
	}

	public void setUserEmail(String userEmail) {
		this.userEmail = userEmail;
	}

	@Column(name = "user_phone_number", nullable = false, length = 20)
	public String getUserPhoneNumber() {
		return this.userPhoneNumber;
	}

	public void setUserPhoneNumber(String userPhoneNumber) {
		this.userPhoneNumber = userPhoneNumber;
	}

	@Column(name = "user_motto", nullable = false)
	public String getUserMotto() {
		return this.userMotto;
	}

	public void setUserMotto(String userMotto) {
		this.userMotto = userMotto;
	}

	@Column(name = "user_linked_in_url")
	public String getUserLinkedInUrl() {
		return this.userLinkedInUrl;
	}

	public void setUserLinkedInUrl(String userLinkedInUrl) {
		this.userLinkedInUrl = userLinkedInUrl;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "user_birthdate", length = 13)
	public Date getUserBirthdate() {
		return this.userBirthdate;
	}

	public void setUserBirthdate(Date userBirthdate) {
		this.userBirthdate = userBirthdate;
	}

	@Column(name = "user_birthplace", length = 50)
	public String getUserBirthplace() {
		return this.userBirthplace;
	}

	public void setUserBirthplace(String userBirthplace) {
		this.userBirthplace = userBirthplace;
	}

	@Column(name = "user_gender")
	public Short getUserGender() {
		return this.userGender;
	}

	public void setUserGender(Short userGender) {
		this.userGender = userGender;
	}

	@Column(name = "user_address")
	public String getUserAddress() {
		return this.userAddress;
	}

	public void setUserAddress(String userAddress) {
		this.userAddress = userAddress;
	}

	@Column(name = "user_postal_code", length = 10)
	public String getUserPostalCode() {
		return this.userPostalCode;
	}

	public void setUserPostalCode(String userPostalCode) {
		this.userPostalCode = userPostalCode;
	}

	@Column(name = "user_feedback_method", length = 100)
	public String getUserFeedbackMethod() {
		return this.userFeedbackMethod;
	}

	public void setUserFeedbackMethod(String userFeedbackMethod) {
		this.userFeedbackMethod = userFeedbackMethod;
	}

	@Column(name = "user_lifestyle_aspiration", length = 100)
	public String getUserLifestyleAspiration() {
		return this.userLifestyleAspiration;
	}

	public void setUserLifestyleAspiration(String userLifestyleAspiration) {
		this.userLifestyleAspiration = userLifestyleAspiration;
	}

	@Column(name = "user_redflags", length = 100)
	public String getUserRedflags() {
		return this.userRedflags;
	}

	public void setUserRedflags(String userRedflags) {
		this.userRedflags = userRedflags;
	}

	@Column(name = "user_predictable_time_off", length = 100)
	public String getUserPredictableTimeOff() {
		return this.userPredictableTimeOff;
	}

	public void setUserPredictableTimeOff(String userPredictableTimeOff) {
		this.userPredictableTimeOff = userPredictableTimeOff;
	}

	@Column(name = "user_image_profile")
	public String getUserImageProfile() {
		return this.userImageProfile;
	}

	public void setUserImageProfile(String userImageProfile) {
		this.userImageProfile = userImageProfile;
	}

	@Column(name = "user_marital_status")
	public Short getUserMaritalStatus() {
		return this.userMaritalStatus;
	}

	public void setUserMaritalStatus(Short userMaritalStatus) {
		this.userMaritalStatus = userMaritalStatus;
	}

	@Column(name = "is_active")
	public Short getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Short isActive) {
		this.isActive = isActive;
	}

	@Column(name = "is_fresh_user")
	public Short getIsFreshUser() {
		return this.isFreshUser;
	}

	public void setIsFreshUser(Short isFreshUser) {
		this.isFreshUser = isFreshUser;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<UserRole> getUserRoles() {
		return this.userRoles;
	}

	public void setUserRoles(Set<UserRole> userRoles) {
		this.userRoles = userRoles;
	}
	
	@Column(name = "password", nullable = false)
	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}
	
	@Column(name = "user_real_name", nullable = false)
	public String getUserRealName() {
		return userRealName;
	}

	public void setUserRealName(String userRealName) {
		this.userRealName = userRealName;
	}
	
	@Column(name = "created_date", columnDefinition = "DATE")
	public Date getCreatedDate() {
		return createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}
	
	@Column(name = "created_by")
	public String getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}
	
	@Column(name = "updated_date", columnDefinition = "DATE")
	public Date getUpdatedDate() {
		return updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}
	
	@Column(name = "updated_by")
	public String getUpdatedBy() {
		return updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}
	
	

}
